# Imports

In [1]:
 config = {
    'gdt': {
        'depth': 10,
        
        'learning_rate_index': 0.05,
        'learning_rate_values': 0.01,
        'learning_rate_leaf': 0.05,
        
        'split_index_activation': 'entmax',
                
        'optimizer': 'SWA', #adam with stochastic weight averaging
        
        'initializer': 'GlorotUniform', 
        
        'dropout': 0,
        
        'prunePostHoc': True,
        'prune_threshold': 1,
        
        'batch_size': 128,#512,
        'epochs': 10_000,
        
        'loss': 'binary_focal_crossentropy', #binary_focal_crossentropy, binary_crossentropy
        
        'focalLossGamma': 3,
        
        'polyLoss': False,
        'polyLossEpsilon': 2,
        
        'restarts': 3,
        'restart_type': 'loss', #'loss', 'metric'
        
        'early_stopping_epochs': 200,
        'early_stopping_type': 'loss', #'loss', 'metric'
        'early_stopping_epsilon': 0.0,
    },
    
    'preprocessing': {
        'balance_threshold': 0.25,#.25, #if minclass fraction less than threshold/num_classes-1 | #0=no rebalance, 1=rebalance all
        'normalization_technique': 'quantile', #'min-max'
        'quantile_noise': 1e-3,
    },

    'computation': {
        'random_seed': 42,
        'trials': 10,
        
        'use_best_hpo_result': False,
        'hpo_path': '_DEFAULT',
        
        'force_depth': False,
        'force_dropout': False,
        'force_restart': True,   
        
        'use_gpu': True,
        'gpu_numbers': '0',#'1',
        'n_jobs': 10,
        'verbosity': 0,
        
        'hpo': None,
        'search_iterations': 300,
        'cv_num': 3,     
        
        'metrics_class': ['f1', 'roc_auc', 'accuracy', 'total_nodes','internal_node_num', 'leaf_node_num'],      
        'eval_metric_class': ['f1', 'roc_auc', 'accuracy', 'total_nodes', 'internal_node_num', 'leaf_node_num'], #f1 accuracy
    },
    
    'benchmarks': {
        'DNDT': True,
        'GeneticTree': True,
        'DL85': True,
        
        'sklearn': True,
        
        'NeuralNetwork': False,
    }
}

In [2]:
import numpy as np
np.set_printoptions(suppress=True)

import sklearn
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split, ParameterGrid, ParameterSampler, GridSearchCV, RandomizedSearchCV, StratifiedKFold
from sklearn.tree import DecisionTreeClassifier, plot_tree, DecisionTreeRegressor
from sklearn.metrics import accuracy_score, f1_score, make_scorer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler, LabelEncoder, OrdinalEncoder
from pydl85 import DL85Classifier

from livelossplot import PlotLosses

import os
from tqdm.notebook import tqdm
from matplotlib import pyplot as plt

from IPython.display import Image
from IPython.display import display, clear_output

import pandas as pd

if config['computation']['use_gpu']:
    os.environ['CUDA_VISIBLE_DEVICES'] = str(config['computation']['gpu_numbers'])
    os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'
    os.environ['XLA_FLAGS'] = "--xla_gpu_cuda_data_dir=/usr/local/cuda-11.6"
    os.environ['TF_XLA_FLAGS'] = "--tf_xla_enable_xla_devices --tf_xla_auto_jit=2"    
else:
    os.environ['CUDA_VISIBLE_DEVICES'] = ''
    os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'false' 
#os.environ['TF_XLA_FLAGS'] = "--tf_xla_auto_jit=2 --tf_xla_cpu_global_jit" 


import warnings
warnings.filterwarnings('ignore')
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 
os.environ["PYTHONWARNINGS"] = "ignore"
import logging

import tensorflow as tf
import tensorflow_addons as tfa

tf.get_logger().setLevel('ERROR')
tf.autograph.set_verbosity(3)

np.seterr(all="ignore")

from keras import backend as K

import seaborn as sns
sns.set_style("darkgrid")

import time
import random

from utilities.utilities_GDT import *
from utilities.GDT import *
from utilities.DNDT import *

from joblib import Parallel, delayed

from itertools import product
from collections.abc import Iterable

from copy import deepcopy
from pathlib import Path
import pickle
import dill

tf.random.set_seed(config['computation']['random_seed'])
np.random.seed(config['computation']['random_seed'])
random.seed(config['computation']['random_seed'])
tf.keras.utils.set_random_seed(config['computation']['random_seed'])

from datetime import datetime
timestr = datetime.utcnow().strftime('%Y-%m-%d--%H-%M-%S%f')
print(timestr)
os.makedirs(os.path.dirname("./evaluation_results" + config['computation']['hpo_path'] + "/latex_tables/" + timestr +"/"), exist_ok=True)

filepath = './evaluation_results' + config['computation']['hpo_path'] + '/depth' + str(config['gdt']['depth']) + '/' + timestr + '/'
Path(filepath).mkdir(parents=True, exist_ok=True)    

pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)

from joblib.externals.loky import set_loky_pickler
set_loky_pickler("dill")

2023-04-28--19-53-11185671

In [3]:
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
print("Num XLA-GPUs Available: ", len(tf.config.experimental.list_physical_devices('XLA_GPU')))

Num GPUs Available:  1
Num XLA-GPUs Available:  1

# Evaluation

## Real-World Eval

### Classification

In [4]:
identifier_list_classification_multi = [
                        'MULT:Iris',# 150 4 3
                        'MULT:Balance Scale',# 625 4 3
                        'MULT:Car',# 1728 6 4
                        'MULT:Glass',# 214 9 6 
                        'MULT:Contraceptive',# 1473 9 3 
                        'MULT:Solar Flare',# 1389 10 8
                        'MULT:Wine',# 178 12 3
                        'MULT:Zoo',#101 16 7   ###TD
                        'MULT:Lymphography',# 148 18 4 ###TD
                        'MULT:Segment',# 2310 19 7
                        'MULT:Dermatology',# 366 34 6
                        'MULT:Landsat',# 6435 36 6
                        'MULT:Annealing',# 798 38 5
                        'MULT:Splice',# 3190 60 3
                  ]

In [5]:

benchmark_dict = get_benchmark_dict(config=config, eval_identifier='classification')

metrics = ['f1', 'roc_auc', 'accuracy']

parallel_eval_real_world = Parallel(n_jobs=min(config['computation']['n_jobs'], config['computation']['trials']), verbose=3, backend='loky') #loky #sequential multiprocessing
evaluation_results_real_world_classification_multi = parallel_eval_real_world(delayed(evaluate_real_world_parallel_nested)(identifier_list=identifier_list_classification_multi[::-1], 
                                                                                                       random_seed_data=config['computation']['random_seed']+i,
                                                                                                       random_seed_model=config['computation']['random_seed'],
                                                                                                       config = config,
                                                                                                       benchmark_dict = benchmark_dict,
                                                                                                       metrics = config['computation']['metrics_class'],
                                                                                                       verbosity = -1) for i in range(config['computation']['trials']))

[Parallel(n_jobs=10)]: Using backend LokyBackend with 10 concurrent workers.
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed: 73.2min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed: 77.9min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed: 78.3min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed: 79.0min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed: 81.2min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed: 84.1min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed: 84.5min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed: 84.6min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed: 86.3min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed: 89.7min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed: 89.7min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed: 90.2min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed: 90.7min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed: 92.2min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed: 92.7min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed: 92.8min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed: 96.0min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed: 96.4min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed: 97.1min remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed: 98.6min remaining:    0.0s
[Parallel(n_jobs=1)]: Done  14 out of  14 | elapsed: 142.2min finished
[Parallel(n_jobs=1)]: Done  14 out of  14 | elapsed: 142.8min finished
[Parallel(n_jobs=1)]: Done  14 out of  14 | elapsed: 148.4min finished
[Parallel(n_jobs=10)]: Done   3 out of  10 | elapsed: 148.5min remaining: 346.5min
[Parallel(n_jobs=1)]: Done  14 out of  14 | elapsed: 156.0min finished
[Parallel(n_jobs=1)]: Done  14 out of  14 | elapsed: 157.7min finished
[Parallel(n_jobs=1)]: Done  14 out of  14 | elapsed: 158.3min finished
[Parallel(n_jobs=1)]: Done  14 out of  14 | elapsed: 160.4min finished
[Parallel(n_jobs=10)]: Done   7 out of  10 | elapsed: 160.6min remaining: 68.8min
[Parallel(n_jobs=1)]: Done  14 out of  14 | elapsed: 161.7min finished
[Parallel(n_jobs=1)]: Done  14 out of  14 | elapsed: 162.1min finished
[Parallel(n_jobs=1)]: Done  14 out of  14 | elapsed: 162.8min finished
[Parallel(n_jobs=10)]: Done  10 out of  10 | elapsed: 162.9min finished

In [6]:
plot_table_save_results(benchmark_dict=benchmark_dict,
                        evaluation_results_real_world=evaluation_results_real_world_classification_multi,
                        identifier_list=identifier_list_classification_multi,                            
                        identifier_string='multi_test',
                        filepath=filepath,
                        config=config)      

plot_table_save_results(benchmark_dict=benchmark_dict,
                        evaluation_results_real_world=evaluation_results_real_world_classification_multi,
                        identifier_list=identifier_list_classification_multi,                            
                        identifier_string='multi_valid',
                        filepath=filepath,
                        config=config)  

plot_table_save_results(benchmark_dict=benchmark_dict,
                        evaluation_results_real_world=evaluation_results_real_world_classification_multi,
                        identifier_list=identifier_list_classification_multi,                            
                        identifier_string='multi_train',
                        filepath=filepath,
                        config=config)

In [7]:
from numba import cuda 
if config['computation']['use_gpu']:
    device = cuda.get_current_device()
    device.reset()